name: OptiGuild
main: io.github.Nick3306.OptiGuild.Main
version: .01
commands:
   guild:
      description: A guild System
      usage:
      permission: 
      permission-message:
   g:
      description: A guild System
      usage:
      permission: 
      permission-message: